package bawei.com.electronicmall.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bawei.com.electronicmall.daobean.SearchGoodsFragmentdaobean;

import bawei.com.electronicmall.greendao.SearchGoodsFragmentdaobeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchGoodsFragmentdaobeanDaoConfig;

    private final SearchGoodsFragmentdaobeanDao searchGoodsFragmentdaobeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchGoodsFragmentdaobeanDaoConfig = daoConfigMap.get(SearchGoodsFragmentdaobeanDao.class).clone();
        searchGoodsFragmentdaobeanDaoConfig.initIdentityScope(type);

        searchGoodsFragmentdaobeanDao = new SearchGoodsFragmentdaobeanDao(searchGoodsFragmentdaobeanDaoConfig, this);

        registerDao(SearchGoodsFragmentdaobean.class, searchGoodsFragmentdaobeanDao);
    }
    
    public void clear() {
        searchGoodsFragmentdaobeanDaoConfig.clearIdentityScope();
    }

    public SearchGoodsFragmentdaobeanDao getSearchGoodsFragmentdaobeanDao() {
        return searchGoodsFragmentdaobeanDao;
    }

}
